export const EnvVariables = {
	NODE_MODE: 'NODE_MODE',
	DOMAIN_URL: 'DOMAIN_URL',
	SERVER_PORT: 'SERVER_PORT',
	MONGODB_URL: 'MONGODB_URL',
	BOT_URL: 'BOT_URL',
	OPENSEA_TOKEN: 'OPENSEA_TOKEN',
	TG_BOT_TOKEN: 'TG_BOT_TOKEN',
	JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
	JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
	REDIS_HOST: 'REDIS_HOST',
	REDIS_PORT: 'REDIS_PORT',
	REDIS_PASSWORD: 'REDIS_PASSWORD'
}