version: '3.8'
networks:
  main:
    driver: bridge
    name: main

services:

  nginx:
    image: nginx:1.27.3
    depends_on: 
      - bot
      - server
      - client
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist:/usr/share/nginx/html:ro
    ports:
      - ${TUNNEL_PORT}:${TUNNEL_PORT}
      - "443:443"
    networks:
      - main

  ngrok:
    image: ngrok/ngrok:3.19.0-alpine
    volumes:
      - ./ngrok.yml:/var/lib/ngrok/ngrok.yml
    command: ["start", "web", "--authtoken", "${NGROK_TOKEN}"]
    networks:
      - main

  bot:
    build:
      context: ./bot
    depends_on:
      - server
    environment:
      - TG_TOKEN=${TG_BOT_TOKEN}
      - DOMAIN_URL=${NGROK_STATIC_DOMAIN}
      - SERVER_URL=http://server:${SERVER_PORT}
      - TG_BOT_PORT=${TG_BOT_PORT}
    networks:
      - main

  server:
    build:
      context: ./server
    depends_on:
      - mongodb
      - redis
    environment:
      - DOMAIN_URL=${NGROK_STATIC_DOMAIN}
      - SERVER_PORT=${SERVER_PORT}

      - MONGODB_URL=mongodb://${DB_USER}:${DB_PASS}@mongodb:${DB_PORT}/${DB_DATABASE}?authSource=${DB_DATABASE}&directConnection=true
      - BOT_URL=http://bot:${TG_BOT_PORT}

      - OPENSEA_TOKEN=${OPENSEA_TOKEN}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - main

  client:
    build:
      context: ./client
    networks:
      - main

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
      MONGO_DB_USERNAME: ${DB_USER}
      MONGO_DB_PASSWORD: ${DB_PASS}
    command: ["mongod", "--config", "/config/mongod.conf"]
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongod.conf:/config/mongod.conf:ro
      - ./data/db-data/db:/data/db
    networks:
      - main

  redis:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - ./data/redis:/data
    networks:
      - main

    
