

POST http://localhost:25001/api/v1/auth/bot-login 
Content-Type: application/json
{
    "userId": 654321
}

POST http://localhost:25001/api/v1/auth/refresh
Content-Type: application/json
{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM3NDc0MDk2OCwiaWF0IjoxNzQ3MTMwMzUxLCJleHAiOjE3NDk3MjIzNTF9.ffpScr0sh5upt6OmFrqLAdNK9CY1oeR7eqQlriQlJkc"
}

GET http://localhost:25001/api/v1/subscriptions/6824b956fc2c6da9c180e811
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODI0YzAxNTRhY2ZkMGI4ZjZjZTFlZGYiLCJ1c2VySWQiOjY1NDMyMSwiY3JlYXRlZEF0IjoiMjAyNS0wNS0xNFQxNjowODo1My45NTdaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0xNFQxNjowODo1My45NTdaIiwiX192IjowLCJpYXQiOjE3NDczMTc4MjksImV4cCI6MTc0NzMxOTYyOX0.FqvysgaMyMuhjPoZOsJPlueMIGJQgaZ-k_t2cEBYZu4



GET http://localhost:25001/api/v1/collection/gemesis
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIzMGY2OThhZTZiMWU3YTdhMTZlMGUiLCJ1c2VySWQiOjEyMzQ1NiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0xM1QwOToyMjo0OS41MTZaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0xM1QwOToyMjo0OS41MTZaIiwiX192IjowLCJpYXQiOjE3NDcyMzcwMTksImV4cCI6MTc0NzIzODgxOX0.92_KgNAs_xMOWp1x8YTPRxRpdhrMU6o-HCvNYFKmmxo

POST http://localhost:25001/api/v1/subscriptions/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjY1NDMyMSwiaWF0IjoxNzQ3MjM4OTMzLCJleHAiOjE3NDcyNDA3MzN9.5WfgD9IMX2KenapxPcymbSY9A3HWSsYkoBybPH2IVRk
{
		"target": {
			"type": "nft",
			"slug": "gemesis",
			"name": "Gemesis",
			"chain": "ethereum",
			"symbol": "ETH",
			"lastNotifiedPrice": 0.0206999
		},
		"strategy": {
			"type": "percentage",
			"threshold": 10
		}
		
}

PUT http://localhost:25001/api/v1/subscriptions/change_status/6824b956fc2c6da9c180e811
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODI0YzAxNTRhY2ZkMGI4ZjZjZTFlZGYiLCJ1c2VySWQiOjY1NDMyMSwiY3JlYXRlZEF0IjoiMjAyNS0wNS0xNFQxNjowODo1My45NTdaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0xNFQxNjowODo1My45NTdaIiwiX192IjowLCJpYXQiOjE3NDczMTc4MjksImV4cCI6MTc0NzMxOTYyOX0.FqvysgaMyMuhjPoZOsJPlueMIGJQgaZ-k_t2cEBYZu4

PUT http://localhost:25001/api/v1/strategy/update/nft/snackgang-official
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODI0YzAxNTRhY2ZkMGI4ZjZjZTFlZGYiLCJ1c2VySWQiOjY1NDMyMSwiY3JlYXRlZEF0IjoiMjAyNS0wNS0xNFQxNjowODo1My45NTdaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0xNFQxNjowODo1My45NTdaIiwiX192IjowLCJpYXQiOjE3NDczMTc4MjksImV4cCI6MTc0NzMxOTYyOX0.FqvysgaMyMuhjPoZOsJPlueMIGJQgaZ-k_t2cEBYZu4

// 6824b956fc2c6da9c180e811