

POST http://localhost:25001/api/v1/auth/bot-login 
Content-Type: application/json
{
    "userId": 374740968
}

POST http://localhost:25001/api/v1/auth/refresh
Content-Type: application/json
{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM3NDc0MDk2OCwiaWF0IjoxNzQ3MTMwMzUxLCJleHAiOjE3NDk3MjIzNTF9.ffpScr0sh5upt6OmFrqLAdNK9CY1oeR7eqQlriQlJkc"
}

GET http://localhost:25001/api/v1/collection/gemesis
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM3NDc0MDk2OCwiaWF0IjoxNzQ3MTM5MDU0LCJleHAiOjE3NDcxNDA4NTR9.YYS0cI7UBnNvOfKTzgETfmMIOKEi3N1arxbDeSRuRw0

GET http://localhost:25001/api/v1/subscriptions?userId=374740968
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM3NDc0MDk2OCwiaWF0IjoxNzQ3MTM5MDU0LCJleHAiOjE3NDcxNDA4NTR9.YYS0cI7UBnNvOfKTzgETfmMIOKEi3N1arxbDeSRuRw0
